# Generated by Django 5.1.7 on 2025-04-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrasiRekamMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=10)),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True)),
                ('no_hp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jenis_kepesertaan', models.CharField(blank=True, choices=[('kis', 'Kartu Indonesia Sehat (KIS)'), ('jamkesda', 'Jaminan Kesehatan Daerah (Jamkesda)'), ('jknbpjs', 'JKN - BPJS Kesehatan'), ('bpjsket', 'BPJS Ketenagakerjaan')], max_length=30, null=True)),
                ('nomor_kartu', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_kontak_darurat', models.CharField(blank=True, max_length=100, null=True)),
                ('hubungan_kontak', models.CharField(blank=True, choices=[('suami', 'Suami'), ('istri', 'Istri'), ('ayah', 'Ayah'), ('ibu', 'Ibu'), ('etc', 'Lainnya')], max_length=20, null=True)),
                ('no_hp_kontak', models.CharField(blank=True, max_length=20, null=True)),
                ('riwayat_penyakit', models.TextField(blank=True, null=True)),
                ('alergi_obat_makanan', models.TextField(blank=True, null=True)),
                ('riwayat_operasi', models.TextField(blank=True, null=True)),
                ('riwayat_pengobatan', models.TextField(blank=True, null=True)),
                ('merokok', models.BooleanField(null=True)),
                ('konsumsi_alkohol', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('gol_darah', models.CharField(max_length=3)),
                ('no_hp', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jenis_kepesertaan', models.CharField(max_length=100)),
                ('nomor_kartu', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_kontak_darurat', models.CharField(max_length=100)),
                ('hubungan_kontak', models.CharField(max_length=50)),
                ('no_hp_kontak', models.CharField(max_length=20)),
                ('riwayat_penyakit', models.TextField(blank=True, null=True)),
                ('alergi', models.TextField(blank=True, null=True)),
                ('riwayat_operasi', models.TextField(blank=True, null=True)),
                ('riwayat_pengobatan', models.TextField(blank=True, null=True)),
                ('merokok', models.CharField(max_length=10)),
                ('alkohol', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
