# Generated by Django 5.1.7 on 2025-04-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministrasiRekamMedis',
            new_name='AdmRekamMedisPasien',
        ),
        migrations.DeleteModel(
            name='Pasien',
        ),
    ]
