# Generated by Django 5.1.7 on 2025-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_administrasirekammedis_admrekammedispasien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admrekammedispasien',
            name='konsumsi_alkohol',
            field=models.CharField(choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admrekammedispasien',
            name='merokok',
            field=models.CharField(choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=10),
        ),
    ]
