# Generated by Django 5.1.7 on 2025-04-06 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_admrekammedispasien_konsumsi_alkohol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admrekammedispasien',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rekam_medis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
