# Generated by Django 5.1.7 on 2025-04-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_meetingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='jadwal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests_patient', to='doctor.jadwaldokter'),
            preserve_default=False,
        ),
    ]
